name:                spot-on
version:             0.1.0.0
github:              "MiksuR/spot-on"
license:             BSD3
author:              "Miksu Rankaviita"
maintainer:          ""
copyright:           "2023 Miksu Rankaviita"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/MiksuR/spot-on#readme>

dependencies:
- base >= 4.7 && < 5
- extra >= 1.7
- dbus >= 1.2
- optparse-applicative >= 0.18
- process >= 1.6

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  spot-on-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - spot-on

tests:
  spot-on-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - spot-on
